name: Get Merged PR Labels on Push to Main

on:
  push:
    branches:
      - main

jobs:
  get-pr-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find Merged PR by merge_commit_sha
        id: find_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = context.sha;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              sort: "updated",
              direction: "desc",
              per_page: 50
            });

            const pr = prs.find(p => p.merge_commit_sha === commitSha);
            if (!pr) {
              core.setOutput("labels", "");
              core.warning("No merged PR found for this commit.");
              return;
            }

            const labels = pr.labels.map(l => l.name);
            core.setOutput("labels", labels.join(","));
            core.setOutput("pr_number", pr.number);
            console.log(`PR #${pr.number} labels: ${labels.join(", ")}`);

      - name: Print PR labels
        run: |
          echo "PR #${{ steps.find_pr.outputs.pr_number }} had labels: ${{ steps.find_pr.outputs.labels }}"
