name: Conditional Jobs Based on Exact PR Labels

on:
  push:
    branches:
      - main

jobs:
  get-pr-labels:
    runs-on: ubuntu-latest
    outputs:
      labels_json: ${{ steps.find_pr.outputs.labels_json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find Merged PR and Extract Labels
        id: find_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = context.sha;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              sort: "updated",
              direction: "desc",
              per_page: 50
            });

            const pr = prs.find(p => p.merge_commit_sha === commitSha);
            if (!pr) {
              core.setOutput("labels_json", "[]");
              core.warning("No merged PR found for this commit.");
              return;
            }

            const labels = pr.labels.map(l => l.name);
            core.setOutput("labels_json", JSON.stringify(labels));
            console.log(`PR #${pr.number} labels: ${labels.join(", ")}`);

  job1:
    needs: get-pr-labels
    runs-on: ubuntu-latest
    if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job1') }}
    steps:
      - name: Step 1 of Job 1
        if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job1-step1') }}
        run: echo "Running step 1 of job 1"

      - name: Step 2 of Job 1
        if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job1-step2') }}
        run: echo "Running step 2 of job 1"

  job2:
    needs: get-pr-labels
    runs-on: ubuntu-latest
    if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job2') }}
    steps:
      - name: Step 1 of Job 2
        if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job2-step1') }}
        run: echo "Running step 1 of job 2"

      - name: Step 2 of Job 2
        if: ${{ !fromJSON(needs.get-pr-labels.outputs.labels_json).includes('skip-job2-step2') }}
        run: echo "Running step 2 of job 2"
